[build]
  base = "./"
  publish = "/app/dist/"
  command = "cd app && npm install && npm run build"
  environment = { NODE_ENV = "development", NODE_VERSION = "14.15.3" }
  
  functions = "functions"

[context.master]
  environment = { NODE_ENV = "production" }


[[redirects]]
  from = "/api/*"
  to = "https://denis-easy.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [redirects.headers]
  X-From = "Netlify"